version: 0.2

phases:
  install:
    commands:
      - rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
      - rpm -Uvh https://dev.mysql.com/get/mysql80-community-release-el7-11.noarch.rpm
      - yum update -y
      - yum install -y mysql-community-client
  pre_build:
    commands:
      - echo 'Hello World (PRE_BUILD phase)'
  build:
    commands:
      - echo 'Hello World (BUILD phase)'
  post_build:
    commands:
      - echo 'Hello World (POST_BUILD phase)'
