version: 0.2

phases:
  install:
    commands:
      - wget https://dev.mysql.com/get/mysql80-community-release-el7-11.noarch.rpm
      - yum localinstall -y mysql80-community-release-el7-11.noarch.rpm
      - yum install -y mysql-community-client
  pre_build:
    commands:
      - echo 'Hello World (PRE_BUILD phase)'
  build:
    commands:
      - echo 'Hello World (BUILD phase)'
  post_build:
    commands:
      - echo 'Hello World (POST_BUILD phase)'
