version: 0.2

phases:
  install:
    commands:
      - sudo yum install -y mariadb mariadb-client
      - mysql --version
  pre_build:
    commands:
      - echo 'Hello World (PRE_BUILD phase)'
  build:
    commands:
      - echo 'Hello World (BUILD phase)'
  post_build:
    commands:
      - echo 'Hello World (POST_BUILD phase)'
